### ISSUE TITLE
Description window closed when moving mouse away from the description tab

### ISSUE THREAD

**Issue by tyrinwu** [williamyeny/duke-registration-enhancer#25]
While trying to copy information from the description window, I moved the mouse away toward the newly opened description window, then the description window is closed immediately.

Guess we can make the window stick there if we move the mouse on it?

**Comment by williamyeny** [comment]
I created an option for users to click on the button instead of hovering so they can copy + paste (check the extension options). Then, they can click outside of the tooltip to close it.

We plan on making the options page more visible so users know that they can change it to click.

However, having the window stick is a great idea! If I modify the CSS a bit to have the tooltip "attached" to the badge, users can float over the tooltip itself.

For reference, here's what I mean by badges/tooltips:
![tooltipsandbadges](http://i.imgur.com/Nlb6jZc.png)

Thanks for the issue

**Comment by tyrinwu** [comment]
Hey, no problem. Thanks for sharing the thoughts.

_However, having the window stick is a great idea! If I modify the CSS a bit to have the tooltip "attached" to the badge, users can float over the tooltip itself._

I can totally see how this idea work!

**Comment by williamyeny** [comment]
I updated the look so you can float over the tooltip. Not the prettiest solution in the world, but I will improve it later on.

![connected-tooltip](http://i.imgur.com/sXfeuGP.png)

**Comment by williamyeny** [comment]
Future plan: adding an invisible pseudo element (:after) to the description badge when it is hovering and putting the tooltip "triangle" back, kind of like an invisible bridge, which let's us use the aesthetic triangle.

**Comment by williamyeny** [comment]
Implemented the above: when hovering over, an invisible element "extends" the badge, allowing you to hover over it to the tooltip without the tooltip disappearing.

Invisible element highlighted in red:

![invisible-element](http://i.imgur.com/fMmW4ws.png)
